language: php

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs

php:
  - 7.0
  - 7.1
  - 7.2
